2018-10-19 08:17:40 ERROR    Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 507, in Stat_Browse_Clicked
    self.Stat_To_Convert.setText(filename[0])
IndexError: list index out of range
Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 507, in Stat_Browse_Clicked
    self.Stat_To_Convert.setText(filename[0])
IndexError: list index out of range
2018-10-19 08:17:49 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 68, in Stitcher
    dataout.to_csv(output_filename)
UnboundLocalError: local variable 'dataout' referenced before assignment
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 68, in Stitcher
    dataout.to_csv(output_filename)
UnboundLocalError: local variable 'dataout' referenced before assignment
2018-10-19 08:18:24 ERROR    Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 507, in Stat_Browse_Clicked
    self.Stat_To_Convert.setText(filename[0])
IndexError: list index out of range
Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 507, in Stat_Browse_Clicked
    self.Stat_To_Convert.setText(filename[0])
IndexError: list index out of range
2018-10-19 08:18:34 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 68, in Stitcher
    dataout.to_csv(output_filename)
UnboundLocalError: local variable 'dataout' referenced before assignment
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 68, in Stitcher
    dataout.to_csv(output_filename)
UnboundLocalError: local variable 'dataout' referenced before assignment
2018-10-19 16:10:15 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
2018-10-19 16:10:25 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
2018-10-19 16:10:27 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
2018-10-19 16:10:27 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
2018-10-19 16:10:27 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
2018-10-19 16:10:28 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
2018-10-19 16:10:28 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
2018-10-19 16:10:28 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split()[0])+1):
ValueError: invalid literal for int() with base 10: '1.1'
2018-10-19 16:11:54 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t
2018-10-19 16:11:57 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t
2018-10-19 16:11:58 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t8.68872066251043\t7.45566426149263\t3.43260513546913\t3.15584048895156\t2.86340274149151\t2.40001154268483\t3.53759076736452\t4.32015773536855\t2.53038275005405\t1.40493979367578\t1.9710262744931
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t8.68872066251043\t7.45566426149263\t3.43260513546913\t3.15584048895156\t2.86340274149151\t2.40001154268483\t3.53759076736452\t4.32015773536855\t2.53038275005405\t1.40493979367578\t1.9710262744931
2018-10-19 16:11:58 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t36.686007837295\t23.5985354085081\t10.6721235693146\t8.92770953178202\t7.25258805714748\t6.6939172794571\t12.1598273785318\t12.7751405419831\t6.96130712540032\t5.15663158967925\t4.45332013127695\
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t36.686007837295\t23.5985354085081\t10.6721235693146\t8.92770953178202\t7.25258805714748\t6.6939172794571\t12.1598273785318\t12.7751405419831\t6.96130712540032\t5.15663158967925\t4.45332013127695\
2018-10-19 16:11:58 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t35.6053632886692\t23.53768740535\t10.2036684910323\t8.82346906768722\t7.06177273938572\t6.04194433486663\t10.7184304097158\t12.1330307023425\t5.8315200959041\t3.47862386719503\t4.22132336195378\t
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t35.6053632886692\t23.53768740535\t10.2036684910323\t8.82346906768722\t7.06177273938572\t6.04194433486663\t10.7184304097158\t12.1330307023425\t5.8315200959041\t3.47862386719503\t4.22132336195378\t
2018-10-19 16:11:59 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t32.0463257589282\t21.4730147763465\t10.8574121633492\t9.30747970285209\t8.08884365146408\t6.8167499439302\t11.4040634003793\t12.8875160115082\t7.17987285225836\t4.2551957204524\t4.86569750607804\
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t32.0463257589282\t21.4730147763465\t10.8574121633492\t9.30747970285209\t8.08884365146408\t6.8167499439302\t11.4040634003793\t12.8875160115082\t7.17987285225836\t4.2551957204524\t4.86569750607804\
2018-10-19 16:11:59 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t0.0733967033433326\t0.0488946786142671\t0\t0.0674954295894246\t0.0209613788275071\t0.0234301970819387\t0.0474155599197733\t0.091762824804204\t0\t0\t0.0397490608839341\t0.025117724765966\t0\t0\t0.
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t0.0733967033433326\t0.0488946786142671\t0\t0.0674954295894246\t0.0209613788275071\t0.0234301970819387\t0.0474155599197733\t0.091762824804204\t0\t0\t0.0397490608839341\t0.025117724765966\t0\t0\t0.
2018-10-19 16:11:59 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t30.6672620601615\t23.8571916226252\t18.9722908895325\t15.372605389099\t13.6274422236063\t12.5815695573273\t15.4803701913283\t17.2639994013579\t11.2847410810828\t8.19273996316356\t8.36061572372422
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 41, in csvformatter
    for recepternum in range(1,int(line.split(":")[-1])+1):
ValueError: invalid literal for int() with base 10: '00\t30.6672620601615\t23.8571916226252\t18.9722908895325\t15.372605389099\t13.6274422236063\t12.5815695573273\t15.4803701913283\t17.2639994013579\t11.2847410810828\t8.19273996316356\t8.36061572372422
2018-10-25 09:19:23 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 54, in csvformatter
    in_txt = csv.reader(open(txt_file, "r"), delimiter = '\t')
FileNotFoundError: [Errno 2] No such file or directory: 'Receptor_timeseries_BlockB_Stack1-2_NOx.txt'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 54, in csvformatter
    in_txt = csv.reader(open(txt_file, "r"), delimiter = '\t')
FileNotFoundError: [Errno 2] No such file or directory: 'Receptor_timeseries_BlockB_Stack1-2_NOx.txt'
2018-10-25 09:19:25 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 54, in csvformatter
    in_txt = csv.reader(open(txt_file, "r"), delimiter = '\t')
FileNotFoundError: [Errno 2] No such file or directory: 'Receptor_timeseries_BlockB_Stack1-2_NOx - Copy.txt'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 54, in csvformatter
    in_txt = csv.reader(open(txt_file, "r"), delimiter = '\t')
FileNotFoundError: [Errno 2] No such file or directory: 'Receptor_timeseries_BlockB_Stack1-2_NOx - Copy.txt'
2018-10-25 09:19:29 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 54, in csvformatter
    in_txt = csv.reader(open(txt_file, "r"), delimiter = '\t')
FileNotFoundError: [Errno 2] No such file or directory: 'Receptor_timeseries_BlockB_Stack1-2_NOx - Copy (2).txt'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 54, in csvformatter
    in_txt = csv.reader(open(txt_file, "r"), delimiter = '\t')
FileNotFoundError: [Errno 2] No such file or directory: 'Receptor_timeseries_BlockB_Stack1-2_NOx - Copy (2).txt'
2018-10-25 09:26:24 ERROR    list index out of range
Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 598, in Stitcher_Run_Clicked
    scalesl.append(row[2])
IndexError: list index out of range
2018-10-25 09:26:27 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 68, in Stitcher
    dataout.to_csv(output_filename)
UnboundLocalError: local variable 'dataout' referenced before assignment
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 68, in Stitcher
    dataout.to_csv(output_filename)
UnboundLocalError: local variable 'dataout' referenced before assignment
2018-10-25 09:31:30 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 69, in Stitcher
    dataout.to_csv(output_filename)
AttributeError: 'NoneType' object has no attribute 'to_csv'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 69, in Stitcher
    dataout.to_csv(output_filename)
AttributeError: 'NoneType' object has no attribute 'to_csv'
2018-10-25 09:32:01 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 69, in Stitcher
    dataout.to_csv(output_filename)
AttributeError: 'NoneType' object has no attribute 'to_csv'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 69, in Stitcher
    dataout.to_csv(output_filename)
AttributeError: 'NoneType' object has no attribute 'to_csv'
2018-10-25 09:36:11 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 62, in Stitcher
    if(dataout.shape != data.shape()):
TypeError: 'tuple' object is not callable
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 62, in Stitcher
    if(dataout.shape != data.shape()):
TypeError: 'tuple' object is not callable
2018-10-25 09:36:49 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 63, in Stitcher
    ErrorBox("Datasets Size Error","Please review data sets size (eg missing hour or day)",err)
UnboundLocalError: local variable 'err' referenced before assignment
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\Stitcher.py", line 63, in Stitcher
    ErrorBox("Datasets Size Error","Please review data sets size (eg missing hour or day)",err)
UnboundLocalError: local variable 'err' referenced before assignment
2018-10-25 09:38:08 ERROR    
NoneType: None
2018-10-25 09:40:08 ERROR    
NoneType: None
2018-10-25 09:41:33 ERROR    Expecting data set size of (8759, 125) 
 Received: (365, 3291)
NoneType: None
2018-10-25 09:59:26 ERROR    Expecting data set size of (8759, 125) 
 Received: (3287, 10)
NoneType: None
2018-10-26 08:46:32 ERROR    Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 698, in MassCSV_Browse_Clicked
    self.MassCSV_Table.setItem(row,2,QTableWidgetItem(filename.split('.')[0] + "_Formatted.csv"))
AttributeError: 'list' object has no attribute 'split'
Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 698, in MassCSV_Browse_Clicked
    self.MassCSV_Table.setItem(row,2,QTableWidgetItem(filename.split('.')[0] + "_Formatted.csv"))
AttributeError: 'list' object has no attribute 'split'
2018-10-26 08:47:12 ERROR    Traceback (most recent call last):
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1790, in _validate_key
    error()
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [Filename] is not in the [columns]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 714, in MassCSV_Import_Clicked
    for filename,calpuff,row in zip(settings.loc[:,'Filename'],settings.loc[:,'XY Included'],range(len(settings.loc[:,'Filename']))):
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1472, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 870, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 998, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1911, in _getitem_axis
    self._validate_key(key, axis)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1798, in _validate_key
    error()
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [Filename] is not in the [columns]'
Traceback (most recent call last):
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1790, in _validate_key
    error()
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [Filename] is not in the [columns]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 714, in MassCSV_Import_Clicked
    for filename,calpuff,row in zip(settings.loc[:,'Filename'],settings.loc[:,'XY Included'],range(len(settings.loc[:,'Filename']))):
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1472, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 870, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 998, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1911, in _getitem_axis
    self._validate_key(key, axis)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1798, in _validate_key
    error()
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\site-packages\pandas\core\indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [Filename] is not in the [columns]'
2018-10-26 08:49:25 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 58, in csvformatter
    in_txt = csv.read(open(txt_file,"r"))
AttributeError: module 'csv' has no attribute 'read'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 58, in csvformatter
    in_txt = csv.read(open(txt_file,"r"))
AttributeError: module 'csv' has no attribute 'read'
2018-10-26 08:49:27 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 58, in csvformatter
    in_txt = csv.read(open(txt_file,"r"))
AttributeError: module 'csv' has no attribute 'read'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 58, in csvformatter
    in_txt = csv.read(open(txt_file,"r"))
AttributeError: module 'csv' has no attribute 'read'
2018-10-26 08:54:22 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 59, in csvformatter
    delimter = sniffer.sniff(in_txt)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\csv.py", line 182, in sniff
    self._guess_quote_and_delimiter(sample, delimiters)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\csv.py", line 223, in _guess_quote_and_delimiter
    matches = regexp.findall(data)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 59, in csvformatter
    delimter = sniffer.sniff(in_txt)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\csv.py", line 182, in sniff
    self._guess_quote_and_delimiter(sample, delimiters)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\csv.py", line 223, in _guess_quote_and_delimiter
    matches = regexp.findall(data)
TypeError: expected string or bytes-like object
2018-10-26 08:54:29 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 59, in csvformatter
    delimter = sniffer.sniff(in_txt)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\csv.py", line 182, in sniff
    self._guess_quote_and_delimiter(sample, delimiters)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\csv.py", line 223, in _guess_quote_and_delimiter
    matches = regexp.findall(data)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 59, in csvformatter
    delimter = sniffer.sniff(in_txt)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\csv.py", line 182, in sniff
    self._guess_quote_and_delimiter(sample, delimiters)
  File "C:\Users\McKewJ\Anaconda\envs\AirQualityToolkit\lib\csv.py", line 223, in _guess_quote_and_delimiter
    matches = regexp.findall(data)
TypeError: expected string or bytes-like object
2018-10-26 08:55:24 ERROR    Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 697, in MassCSV_Browse_Clicked
    self.MassCSV_Table.setItem(row,0,QTableWidgetItem(filename[0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "u:\Git Version Control\Air-Quality-Toolkit\PyQt\PyQt_AirQualityToolkit.py", line 697, in MassCSV_Browse_Clicked
    self.MassCSV_Table.setItem(row,0,QTableWidgetItem(filename[0]))
IndexError: list index out of range
2018-10-26 08:55:48 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 62, in csvformatter
    in_txt = csv.reader(open(txt_file,"r"),delimiter=delimter)
TypeError: "delimiter" must be string, not type
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 62, in csvformatter
    in_txt = csv.reader(open(txt_file,"r"),delimiter=delimter)
TypeError: "delimiter" must be string, not type
2018-10-26 09:14:05 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 62, in csvformatter
    test_csv = csv.reader(open(out_csv),"r")
TypeError: expected str, bytes or os.PathLike object, not _csv.writer
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 62, in csvformatter
    test_csv = csv.reader(open(out_csv),"r")
TypeError: expected str, bytes or os.PathLike object, not _csv.writer
2018-10-26 09:14:46 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 62, in csvformatter
    test_csv = csv.reader(open(outpath),"r")
_csv.Error: unknown dialect
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 62, in csvformatter
    test_csv = csv.reader(open(outpath),"r")
_csv.Error: unknown dialect
2018-10-26 09:18:35 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 58, in csvformatter
    if(delimquestion == QMessageBox.Yes):
UnboundLocalError: local variable 'delimquestion' referenced before assignment
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 58, in csvformatter
    if(delimquestion == QMessageBox.Yes):
UnboundLocalError: local variable 'delimquestion' referenced before assignment
2018-10-26 09:28:12 ERROR    Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 62, in csvformatter
    out_csv = csv.writer(open(outpath, 'w',newline=''))
PermissionError: [Errno 13] Permission denied: 'U:/Git Version Control/Test Datasets/TSERIES_MEBR_24HR_CONC_C_Formatted.csv'
Traceback (most recent call last):
  File "U:\Git Version Control\Air-Quality-Toolkit\CSVFormatter.py", line 62, in csvformatter
    out_csv = csv.writer(open(outpath, 'w',newline=''))
PermissionError: [Errno 13] Permission denied: 'U:/Git Version Control/Test Datasets/TSERIES_MEBR_24HR_CONC_C_Formatted.csv'
